language: python

before_install:
  - nvm install node && nvm use node
  - npm install -g newman

jobs:
  include:
    script: 
      - python app.py &
      - sleep 5
      - newman run ./test-collection.postman_collection.json -e test-env.postman_environment.json